version: "3.9"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - radar-configs:/config
      - /media/external-disk/:/media/external-disk/ #optional
    devices:
      - /dev/sda1:/dev/sda1
    ports:
      - 7878:7878
    restart: unless-stopped
    security_opt: # this option
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '1'
    depends_on:
      - transmission
      - jackett
    extra_hosts:
      - host.docker.internal:host-gateway

  sonarr:
    image: lscr.io/linuxserver/sonarr:3.0.8.1507-ls151
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - sonarr-config:/config
      - /media/external-disk/:/media/external-disk/ #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    extra_hosts:
      - host.docker.internal:host-gateway
    devices:
      - /dev/sda1:/dev/sda1
    security_opt: # this option
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          memory: 180M
          cpus: '1'

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./transmission-config:/config
      - ./transmission-config/settings.json:/config/settings.json:ro
      - /media/external-disk/transmission/downloads:/downloads
      - /media/external-disk/:/media/external-disk/
    devices:
      - /dev/sda1:/dev/sda1
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    security_opt: # this option
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          memory: 50M
          cpus: '1' 
    extra_hosts:
      - host.docker.internal:host-gateway

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - AUTO_UPDATE=false #optional
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    security_opt: # this option
      - seccomp:unconfined
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: '1'
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  radar-configs:
    name: radar-configs
  sonarr-config:
    name: sonarr-config
  jackett-config:
    name: jackett-config
  jackett-downloads:
    name: jackett-downloads
