version: "3.9"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - radar-configs:/config
      - external-drive:/media/external-disk/ #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 110M
          cpus: '1'

    depends_on:
      - transmission
      - jackett
    extra_hosts:
      - host.docker.internal:host-gateway

  sonarr:
    image: lscr.io/linuxserver/sonarr:3.0.8.1507-ls151
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - sonarr-config:/config
      - external-drive:/media/external-disk/ #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - transmission
      - jackett
    extra_hosts:
      - host.docker.internal:host-gateway
    deploy:
      resources:
        limits:
          memory: 150M
          cpus: '1'

  transmission:
    image: lscr.io/linuxserver/transmission:3.00-r5-ls135
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DOWNLOAD_DIR=/media/external-disk/transmission/downloads/complete
      - INCOMPLETE_DIR=/media/external-disk/transmission/downloads/incomplete
    volumes:
      - ./transmission-config/settings-default.json:/defaults/settings.json:ro
      - ./transmission-config:/config
      - ./transmission-config/30-custom-download:/etc/cont-init.d/30-custom-download:ro
      - external-drive:/media/external-disk/
    ports:
      - 9091:9091
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 30M
          cpus: '1' 
    extra_hosts:
      - host.docker.internal:host-gateway

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - AUTO_UPDATE=false #optional
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 125M
          cpus: '1'
    healthcheck:
      test: [ 'CMD', 'sleep', '60']
      timeout: 65s
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  radar-configs:
    name: radar-configs
  sonarr-config:
    name: sonarr-config
  jackett-config:
    name: jackett-config
  jackett-downloads:
    name: jackett-downloads
  external-drive:
    name: external-drive
    driver_opts:
      type: 'ext4'
      device: /dev/sda1
      
